version: '3.9'
services:
  mongodb:
    image: mongo:latest # Use the latest MongoDB image
    container_name: test-mongodb # Give the container a descriptive name
    ports:
      - 27017:27017 # Expose the default MongoDB port
    volumes:
      - ./data/db:/data/db # Persist data in a local directory (optional)
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # Set a root username
      - MONGO_INITDB_ROOT_PASSWORD=password # Set a root password